### ISSUE TITLE
MineBoy V2

### ISSUE THREAD

**Issue by JSH32** [JSH32/MineBoy#8]
Starting work/planning of V2 of MineBoy. There is no ETA, V2 will be a performance, efficiency, and usability update

## TODO
  - [ ] Switch to Rust/Axum for WS server
  - [ ] Use CBOR for protocol instead of BSON
  - [ ] Use [lib_gbemulation](https://github.com/p4ddy1/gbemulator/tree/master/lib_gbemulation) for emulator sessions
  - [ ] Possibly use dioxus (or some other fully server side) for web panel for management of sessions/games
